apiVersion: v1
kind: Pod
metadata:
  name: nodeselectpod
spec:
  containers:
  - name: nodeselectpod
    image: busybox
    command:
    - sh
    - -c
    - echo we are in && sleep 3600 
  nodeSelector:
    nature: worker


# to label a node with key use the below command
# kubectl label node nodename nature:worker
