apiVersion:  v1
kind:  Pod
metadata:
  name:  candy-service-pod
spec:
  securityContext:
    fsGroup:  2000
  serviceAccountName:  candy-svc
  containers:
  - name:  candy-service-pod
    image:  linuxacademycontent/candy-service:1
    command:  ['sh','-c',"echo $DB_PASSWORD $location && sleep 3600"]
    volumeMounts:
    - name: config-volume
      mountPath:  /etc/candy-service
    env:
    - name:  DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name:  db-password
          key:  password
    - name:  location
      valueFrom:
        secretKeyRef:
          name: db-password
          key:  database
    resources:
      requests:
        memory:  "64Mi"  
        cpu:  "250m"
      limits:
        memory:  "128Mi"
        cpu:  "500m"
  volumes:
  - name:  config-volume
    configMap:
      name:  candy-service-config
  
