apiVersion:  v1
kind:  Pod
metadata:
  name:  multicontainerpod
spec:
  containers:
  - name:  nginx
    image:  nginx
    ports:
    - containerPort:  80
  - name: busybox
    image:  busybox
    command:  ['sh','-c',"echo we are inside multicontainer && sleep 3600"]
