apiVersion:  v1
kind:  Pod
metadata:
  name: preposthook
spec:
  containers:
  - name:  lifecycle
    image:  nginx
    lifecycle:
      postStart:
        exec:
          command: 
            - sh
            - -c
            - echo '<h1> postStart hook' > /usr/share/nginx/html/index.html && sleep 20
      preStop:
        exec:
          command:
            - sh
            - -c
            - |
              echo '<h1> postStart hook' > /usr/share/nginx/html/index.html && sleep 20
              nginx -s quit
              while killall -0 nginx;do sleep 1; done
