apiVersion:  v1
kind:  Pod
metadata:
  name:  containerlog
spec:
  containers:
  - name:  containerlog
    image:  busybox
    resources:
      requests:
        memory:  "64Mi"
        cpu:  "250m"
      limits:
        memory:  "128Mi"
        cpu:  "500m"
    command:
      - sh
      - -c
      - |
        i=o; 
        while true;
        do echo "$i: $(date)";
        i=$((i+1));
        sleep 1;
        done

