apiVersion:  v1
kind:  Pod
metadata:
  name:  my-serviceaccountpod
spec:
  serviceAccountName:  my-serviceaccount
  containers:
  - name:  myserviceaccountpod
    image:  busybox
    command:  ['sh','-c',"echo Hello Serviceaccount && sleep 3600"]

