apiVersion:  v1
kind:  Pod
metadata:
  name: myresourcerequest
spec:
  containers:
  - name:  myresourcerequest
    image:  busybox
    command:  ['sh','-c',"echo Hello K8s World && sleep 3600"]
    resources:
      requests:
        memory:  "64Mi"
        cpu:  "250m"
      limits:
        memory:  "128Mi"
        cpu:  "500m"
