apiVersion:  v1
kind:  Pod
metadata:
  name:  my-secret-pod
spec:
  containers:
  - name:  mysecretpod
    image:  busybox
    command:  ['sh','-c',"echo Hello world && echo $MY_PASSWORD && sleep 3600"]
    env:
    - name:  MY_PASSWORD
      valueFrom:
        secretKeyRef:
          name:  my-secret
          key:  anotherKey
